[terminal]
vt = 1

[default_session]
command = "/usr/bin/tuigreet --time --battery --remember --remember-session --sessions /usr/share/wayland-sessions --cmd /usr/bin/start-hyprland"
user = "greeter"
