#!/usr/bin/env bash

set -Eeuo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}/cyrodiil-dotfiles
TIMESTAMP=$(date +%Y%m%d_%H%M%S_%N)
BACKUP_DIR=$STATE_HOME/backups/$TIMESTAMP
MANIFEST=$BACKUP_DIR/manifest.tsv

DRY_RUN=false
ASSUME_YES=false
INSTALL_PACKAGES=true
INSTALL_FIREFOX=true
CONFIGURE_GREETD=true
BACKUP_READY=false

usage() {
    cat <<'EOF'
Usage: ./install.sh [options]

Options:
  --dry-run         Show changes without making them
  --yes             Accept installer prompts
  --no-packages     Skip pacman and AUR package installation
  --skip-firefox    Do not modify a Firefox profile
  --skip-greetd     Keep the current display manager
  -h, --help        Show this help
EOF
}

info() {
    printf '\033[1;34m==>\033[0m %s\n' "$*"
}

success() {
    printf '\033[1;32m ok\033[0m %s\n' "$*"
}

warn() {
    printf '\033[1;33mwarn\033[0m %s\n' "$*" >&2
}

die() {
    printf '\033[1;31merror\033[0m %s\n' "$*" >&2
    exit 1
}

print_command() {
    printf '    '
    printf '%q ' "$@"
    printf '\n'
}

run() {
    if $DRY_RUN; then
        print_command "$@"
    else
        "$@"
    fi
}

confirm() {
    local prompt=$1
    local default=${2:-yes}
    local answer

    $ASSUME_YES && return 0

    if [[ $default == yes ]]; then
        read -r -p "$prompt [Y/n] " answer
        [[ -z $answer || $answer =~ ^[Yy]$ ]]
    else
        read -r -p "$prompt [y/N] " answer
        [[ $answer =~ ^[Yy]$ ]]
    fi
}

ensure_backup() {
    $BACKUP_READY && return
    mkdir -p "$BACKUP_DIR/files"
    chmod 700 "$BACKUP_DIR"
    : > "$MANIFEST"
    printf '%s\n' "$ROOT" > "$BACKUP_DIR/source-root"
    BACKUP_READY=true
}

remember_latest_backup() {
    $BACKUP_READY || return 0
    mkdir -p "$STATE_HOME"
    ln -sfn "$BACKUP_DIR" "$STATE_HOME/latest"
}

on_error() {
    local status=$?
    trap - ERR
    remember_latest_backup
    warn "Installation stopped after an error."
    if $BACKUP_READY; then
        warn "Restore completed changes with: $ROOT/restore.sh $BACKUP_DIR"
    fi
    exit "$status"
}

trap on_error ERR

backup_user_target() {
    local target=$1
    local state=absent
    local backup=$BACKUP_DIR/files/${target#/}

    ensure_backup
    if [[ -e $target || -L $target ]]; then
        state=present
        mkdir -p "$(dirname -- "$backup")"
        cp -a --no-dereference -- "$target" "$backup"
    fi
    printf '%s\t%s\tuser\n' "$target" "$state" >> "$MANIFEST"
}

backup_system_target() {
    local target=$1
    local state=absent
    local backup=$BACKUP_DIR/files/${target#/}

    ensure_backup
    if sudo test -e "$target"; then
        state=present
        mkdir -p "$(dirname -- "$backup")"
        sudo cp -a -- "$target" "$backup"
    fi
    printf '%s\t%s\tsystem\n' "$target" "$state" >> "$MANIFEST"
}

link_path() {
    local source=$1
    local target=$2

    [[ -e $source || -L $source ]] || die "Missing deployment source: $source"

    if [[ -L $target && $(readlink -- "$target") == "$source" ]]; then
        success " $target"
        return
    fi

    if $DRY_RUN; then
        printf ' link %s -> %s\n' "$target" "$source"
        return
    fi

    backup_user_target "$target"
    rm -rf -- "$target"
    mkdir -p "$(dirname -- "$target")"
    ln -s "$source" "$target"
    printf ' link %s -> %s\n' "$target" "$source"
}

install_system_file() {
    local source=$1
    local target=$2
    local mode=${3:-0644}

    [[ -f $source ]] || die "Missing system file: $source"

    if $DRY_RUN; then
        printf ' file %s <- %s\n' "$target" "$source"
        return
    fi

    backup_system_target "$target"
    sudo install -D -m "$mode" "$source" "$target"
    printf ' file %s <- %s\n' "$target" "$source"
}

load_package_file() {
    local file=$1
    local -n output=$2
    local package

    while IFS= read -r package || [[ -n $package ]]; do
        [[ -z $package || $package == \#* ]] && continue
        output+=("$package")
    done < "$file"
}

install_packages() {
    local -a official=()
    local -a aur=()

    load_package_file "$ROOT/packages/pacman.txt" official
    load_package_file "$ROOT/packages/aur.txt" aur

    info "Installing official repository packages"
    run sudo pacman -S --needed "${official[@]}"

    if $DRY_RUN && ! command -v paru >/dev/null; then
        print_command paru -S --needed "${aur[@]}"
        return
    fi

    command -v paru >/dev/null || die "paru was not installed successfully"
    info "Installing AUR themes"
    run paru -S --needed "${aur[@]}"
}

generate_local_config() {
    local target=$ROOT/config/hypr/local.lua

    if [[ -f $target ]]; then
        success " Preserving existing config/hypr/local.lua"
        return
    fi

    if $DRY_RUN; then
        printf ' file %s (generated hardware overrides)\n' "$target"
        return
    fi

    {
        printf '%s\n' '-- Generated by install.sh; this file is intentionally ignored by Git.'
        printf '%s\n' '-- Add exact monitor declarations here after running: hyprctl monitors'
        if lspci 2>/dev/null | grep -qi nvidia; then
            cat <<'EOF'

-- NVIDIA-specific Wayland settings. Driver installation remains system-managed.
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})
EOF
        fi
    } > "$target"
    printf ' file %s\n' "$target"
}

find_firefox_profile() {
    local profiles=$HOME/.mozilla/firefox/profiles.ini
    local record
    local relative
    local path

    [[ -f $profiles ]] || return 1

    path=$(awk -F= '
        /^\[Install/ { install=1; next }
        /^\[/ { install=0 }
        install && $1 == "Default" { print $2; exit }
    ' "$profiles")
    if [[ -n $path ]]; then
        printf '%s\n' "$HOME/.mozilla/firefox/$path"
        return 0
    fi

    record=$(awk -F= '
        function emit() {
            if (section && path != "") {
                if (preferred == "1") print "0\t" relative "\t" path
                else if (name == "default-release") print "1\t" relative "\t" path
            }
        }
        /^\[Profile/ { emit(); section=1; name=""; path=""; preferred=""; relative="1"; next }
        /^\[/ { emit(); section=0; next }
        section && $1 == "Name" { name=$2 }
        section && $1 == "Path" { path=$2 }
        section && $1 == "Default" { preferred=$2 }
        section && $1 == "IsRelative" { relative=$2 }
        END { emit() }
    ' "$profiles" | sort -t $'\t' -k1,1 | head -n 1)

    [[ -n $record ]] || return 1
    IFS=$'\t' read -r _ relative path <<< "$record"

    if [[ $relative == 0 ]]; then
        printf '%s\n' "$path"
    else
        printf '%s\n' "$HOME/.mozilla/firefox/$path"
    fi
}

deploy_files() {
    local name
    local firefox_profile
    local -a config_dirs=(
        ghostty
        gsimplecal
        gtk-3.0
        gtk-4.0
        hypr
        rofi
        swaync
        waybar
        waypaper
    )

    info "Deploying user configuration"
    for name in "${config_dirs[@]}"; do
        link_path "$ROOT/config/$name" "$HOME/.config/$name"
    done

    link_path "$ROOT/config/xdg-desktop-portal/hyprland-portals.conf" \
        "$HOME/.config/xdg-desktop-portal/hyprland-portals.conf"
    link_path "$ROOT/home/.zshrc" "$HOME/.zshrc"
    link_path "$ROOT/home/.icons/default" "$HOME/.icons/default"
    link_path "$ROOT/assets/wallpapers/autumns.hues.png" \
        "$HOME/.local/share/cyrodiil/wallpapers/autumns.hues.png"

    $INSTALL_FIREFOX || return 0
    if firefox_profile=$(find_firefox_profile) && [[ -d $firefox_profile ]]; then
        if confirm "Install the Firefox toolbar theme into the default profile?" yes; then
            link_path "$ROOT/config/firefox/chrome" "$firefox_profile/chrome"
            link_path "$ROOT/config/firefox/user.js" "$firefox_profile/user.js"
        fi
    else
        warn "Firefox profile not found. Launch Firefox once, then rerun the installer."
    fi
}

configure_shell() {
    local zsh_path
    local current_shell

    zsh_path=$(command -v zsh || true)
    [[ -n $zsh_path ]] || return 0
    current_shell=$(getent passwd "$USER" | cut -d: -f7)
    [[ $current_shell != "$zsh_path" ]] || return 0

    if confirm "Make Zsh your login shell?" yes; then
        if $DRY_RUN; then
            print_command chsh -s "$zsh_path" "$USER"
            return
        fi
        ensure_backup
        printf '%s\n' "$current_shell" > "$BACKUP_DIR/login-shell"
        chsh -s "$zsh_path" "$USER"
    fi
}

validate_config() {
    local script

    info "Validating configuration"
    bash -n "$ROOT/install.sh" "$ROOT/restore.sh"
    for script in "$ROOT"/config/hypr/scripts/*.sh "$ROOT"/config/waybar/scripts/*.sh; do
        bash -n "$script"
    done

    command -v zsh >/dev/null && zsh -n "$ROOT/home/.zshrc"
    command -v jq >/dev/null && jq empty "$ROOT/config/swaync/config.json"

    if command -v Hyprland >/dev/null; then
        Hyprland --verify-config --config "$ROOT/config/hypr/hyprland.lua"
    else
        warn "Hyprland is unavailable; config verification was skipped."
    fi
}

configure_greetd() {
    local sddm_state
    local greetd_state

    $CONFIGURE_GREETD || return 0
    confirm "Replace SDDM with greetd on the next boot? Plasma will remain selectable." yes || return 0

    command -v tuigreet >/dev/null || die "tuigreet is not installed"
    command -v start-hyprland >/dev/null || die "start-hyprland is not installed"
    [[ -f /usr/share/wayland-sessions/hyprland.desktop || -f /usr/share/wayland-sessions/hyprland-uwsm.desktop ]] \
        || die "No Hyprland session entry was found"

    install_system_file "$ROOT/system/greetd/config.toml" /etc/greetd/config.toml 0644

    if $DRY_RUN; then
        print_command sudo systemctl disable sddm.service
        print_command sudo systemctl enable greetd.service
        return
    fi

    ensure_backup
    sddm_state=$(systemctl is-enabled sddm.service 2>/dev/null || true)
    greetd_state=$(systemctl is-enabled greetd.service 2>/dev/null || true)
    printf 'sddm=%s\ngreetd=%s\n' "$sddm_state" "$greetd_state" > "$BACKUP_DIR/display-manager"

    sudo systemctl disable sddm.service >/dev/null 2>&1 || true
    if ! sudo systemctl enable greetd.service; then
        warn "Could not enable greetd; restoring SDDM."
        sudo systemctl disable greetd.service >/dev/null 2>&1 || true
        sudo systemctl enable sddm.service
        return 1
    fi

    success " greetd will start on the next boot; SDDM remains installed"
}

while (($#)); do
    case $1 in
        --dry-run) DRY_RUN=true ;;
        --yes) ASSUME_YES=true ;;
        --no-packages) INSTALL_PACKAGES=false ;;
        --skip-firefox) INSTALL_FIREFOX=false ;;
        --skip-greetd) CONFIGURE_GREETD=false ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; die "Unknown option: $1" ;;
    esac
    shift
done

((EUID == 0)) && die "Run this installer as your normal user, not root."
[[ -r /etc/os-release ]] || die "Cannot determine the operating system."

# shellcheck disable=SC1091
source /etc/os-release
if [[ ${ID:-} != cachyos && ${ID:-} != arch && ${ID_LIKE:-} != *arch* ]]; then
    die "This installer supports CachyOS and Arch-based systems only."
fi

printf '\nCyrodiil Dotfiles Installer\n'
printf 'Repository: %s\n' "$ROOT"
printf 'Mode: %s\n\n' "$($DRY_RUN && printf 'dry run' || printf 'install')"

confirm "Continue with the Cyrodiil desktop installation?" yes || exit 0

$INSTALL_PACKAGES && install_packages
generate_local_config
deploy_files
configure_shell
validate_config
configure_greetd
remember_latest_backup

printf '\nInstallation complete.\n'
if $BACKUP_READY; then
    printf 'Backup: %s\n' "$BACKUP_DIR"
    printf 'Restore: %s/restore.sh %s\n' "$ROOT" "$BACKUP_DIR"
fi
printf '\nDo not reboot until you have read the recovery instructions in README.md.\n'
printf 'After reboot, tuigreet can start either Hyprland or Plasma.\n'
